[nitpick]
minimum_version = "0.29.0"

[nitpick.styles]
include = [ "file:///Users/dimaboro/PycharmProjects/bot_moderator/styles/file-structure.toml", "file:///Users/dimaboro/PycharmProjects/bot_moderator/styles/flake8.toml", "file:///Users/dimaboro/PycharmProjects/bot_moderator/styles/darglint.toml", "file:///Users/dimaboro/PycharmProjects/bot_moderator/styles/mypy.toml", "file:///Users/dimaboro/PycharmProjects/bot_moderator/styles/poetry.toml", "file:///Users/dimaboro/PycharmProjects/bot_moderator/styles/styleguide.toml",]

["setup.cfg".flake8]
strictness = "long"
show-source = true
max-line-length = 120
max-complexity = 6
docstring-style = "numpy"
ignore = "D100,D104,D401,W504,RST303,RST304,DAR103,DAR203"

["setup.cfg".mypy]
strict = true
warn_unreachable = true

["setup.cfg".isort]
profile = "wemake"

[nitpick.files.absent]
"requirements.txt" = "Install poetry, run 'poetry init' to create pyproject.toml, and move dependencies to it"
Pipfile = "Use pyproject.toml instead"
"Pipfile.lock" = "Use pyproject.toml instead"
".isort.cfg" = "Move values to setup.cfg, section [isort]"
".flake8" = "Move values to setup.cfg, section [flake8]"
"mypy.ini" = "Move values to setup.cfg, section [mypy]"
".travis.yml" = "Travis is shutting down, please switch to some other CI service"
".pyup.yml" = "Configure your CI with safety instead: https://github.com/pyupio/safety#using-safety-with-a-ci-service"

[nitpick.files.present]
".editorconfig" = "A project should have an editor configuration"
"CHANGELOG.md" = "A project should have `CHANGELOG.md`"
"README.md" = "A project should have `README.md`"
".gitignore" = "A project should have `.gitignore` file"
"pyproject.toml" = "Install poetry and run 'poetry init' to create it"

[nitpick.files."setup.cfg"]
comma_separated_values = [ "flake8.ignore",]
