# `flakeheaven` specific configuration.
# This file is served as `base` config under `[tool.flakeheaven]`

# Make sure to install it with:
# `pip install flakeheaven`

# See:
# https://wemake-python-styleguide.rtfd.io/en/latest/pages/usage/integrations/flakeheaven.html

# This file is not related to `nitpick` at all.
# This file is optional, not required for `flake8` users.

[tool.flakeheaven]
format = "grouped"
show_source = true
statistics = false
doctests = true
enable_extensions = "G"

accept_encodings = "utf-8"
max_complexity = 6
max_line_length = 80

ignore = "D100, D104, D401, W504, RST303, RST304, DAR103, DAR203"

[tool.flakeheaven.plugins]
"flake8-*" = ["+*"]
mccabe = ["+*"]
nitpick = ["+*"]
"pep8-naming" = ["+*"]
pycodestyle = ["+*"]
pyflakes = ["+*"]
"wemake-python-styleguide" = ["+*"]
