# `nitpick` specific configuration.
# `nitpick` ensures that you have the same configuration
# in your own project.

# Make sure to install it with:
# `pip install nitpick`

# See:
# https://wemake-python-styleguide.rtfd.io/en/latest/pages/usage/integrations/nitpick

# This file is included into wemake-preset.

["setup.cfg".mypy]
strict = true
warn_unreachable = true
